### ISSUE TITLE
Tmux freezes Mac when killing a long running session

### ISSUE THREAD

**Issue by dphaener** [tmux/tmux#108]
I have found that when I have a local tmux session running for more than 2-3 hours, and I kill it, my Mac (Running OS X El Capitan GM Candidate) freezes completely. 

Running Tmux 2.0 Stable in Terminal.app (it also happens when using iTerm). 

Additionally, Vim and Terminal apps start becoming sluggish and unresponsive after a session is open for a day or two. I wouldn't mind that too much if I could just kill the session and start it back up again. :)

**Comment by nicm** [comment]
There is no way the freezing is a tmux problem, userspace programs shouldn't be able to do this. Either you are hitting a kernel bug or your hardware is dodgy.

What kind of memory usage is tmux hitting after a day or so? Have you got some ridiculously huge history-limit set?

**Comment by dphaener** [comment]
I'm using the default history-limit (2000). I've heard of a possible kernel bug, but the description I saw didn't look like the same issue I was having. 

I'll keep an eye on the memory usage today (just started a new session about 30 minutes ago) and see if that gives us any more information.

**Comment by pengux** [comment]
I have the same problem. tmux doesn't have high memory usage when this happens. I also have the Activity Monitor open when I close tmux to see if anything suspicious is happening but couldn't find anything off. I ran tmux -vvvv to have logs but the logs doesn't show any errors either. But the problem is very much reproducible, it happens everytime.

**Comment by nicm** [comment]
The freezing? Well, does it happen when you send SIGKILL to tmux? Or on SIGTERM? Or only when you exit all the panes? Does it happen with no .tmux.conf at all? Does it happen on older OS X versions?

**Comment by dphaener** [comment]
@nicm I have just confirmed that killing it via SIGKILL causes a system freeze.

**Comment by nicm** [comment]
You need to go and talk to Apple about this.

-------- Original message --------

**Comment by dphaener** [comment]
Thought that might be the case.......Unfortunately.

**Comment by paulrouget** [comment]
@dphaener do you need to wait 2 hours before this happens? It happens to me imediatly: boot osx 10.11, starts tmux, quit tmux, spinning wheel.

**Comment by dphaener** [comment]
@paulrouget Yes that's correct. I haven't nailed down an exact time, but the session has to be open for some time before this behavior occurs.

**Comment by dphaener** [comment]
@paulrouget Update: Restarting OSX 10.11, opening a tmux session, killing session. This did not cause a full freeze. I then opened a new session. About 10 minutes later, the system began to become unresponsive, slowly. First tmux windows froze, then other programs started to become unresponsive, eventually requiring a full reboot.

**Comment by pengux** [comment]
Actually the problem also occur with SIGTERM, not just SIGKILL. And I've ran tmux without any .tmux.conf too and still the same. As @dphaener reported, it doesn't happens right away, but tmux needs to be open for a while before it starts to slows down and become unresponsive.

**Comment by zacharyvoase** [comment]
I can +1 this. Has anyone filed a Radar yet, or should I? It's unfortunate that it brings the system to a halt but force-rebooting my Mac doesn't cause it to be recognized as a crash, so I don't get any traces/logs.

**Comment by paulrouget** [comment]
> Has anyone filed a Radar yet, or should I?

Please do.

**Comment by zxcvbn97** [comment]
+1 Same problem here

**Comment by pengux** [comment]
A tip for anyone interested. Quitting iTerm2 but not quitting tmux and doing a system restart from Mac OS X doesn't freeze the system. I guess it's a little better than a hard reset.

**Comment by dieyushi** [comment]
same problem here.
10.11.1(15B17c) & tmux2

**Comment by rrva** [comment]
Check if notifyd is using an abnormal amount of CPU when this occurs. That's what I've been seeing.
If I manage to kill notifyd (new one gets auto-respawned) system recovers.

https://forums.developer.apple.com/thread/9753

**Comment by Kudo** [comment]
+1 for the same issue

**Comment by craigp** [comment]
+1 have been suffering with this since the beta, which I wish I'd never installed, ruined my workflow

**Comment by nicm** [comment]
You all need to stop telling me about this and go and tell Apple.

**Comment by Kudo** [comment]
Oops, my fault to bother.  Now I am going to troubleshooting from notifyd as @rrva suggested.
Thanks guys.

**Comment by diversario** [comment]
Same issue here. For me, tmux is slow right from the start – typing take seconds etc. Exiting immediately takes about 10 seconds, after which everything is OK. But exiting a long-running tmux session freezes the entire OS. I also noticed that `notify` is going to 100% CPU while tmux us running.

**Comment by frbl** [comment]
+1

**Comment by wincent** [comment]
> You all need to stop telling me about this and go and tell Apple.

While this definitely looks like an Apple bug (and we should file upstream reports), Apple's release cadence tends to be pretty slow, so if it were possible to isolate the thing that tmux is doing that is causing the Apple bug to manifest that would be good, especially if there were some kind of mitigation that could be implemented.

(FWIW, killing `notifyd` solved the problem instantly for me, and I am not sure how long it will take to return. There might be nefarious consequences to doing that to `notifyd`, but given a choice between those and a total system lockup, there doesn't seem to be much choice, other than not using tmux, which would be basically unthinkable for me.)

**Comment by joshperry** [comment]
Killing notifyd fixes it for me too. Tmux + powerline + iTerm + 10.11

**Comment by appaquet** [comment]
What also helped for me, as I mentioned in https://forums.developer.apple.com/thread/9753, is to increase the status refresh interval (set -g status-interval). It's defaulted to 15 seconds, but it was set to 2 for me as I'm a powerline user. As I'm not really using the powerline's date+time, I bumped it to 60 seconds. It doesn't solve the issue, but as I mentioned in Apple's threads, the context switches and faults count aren't increasing as fast as they were before on notifyd.

**Comment by schaefer-dev** [comment]
where can you report this error to apple? Its driving me crazy if I am using my 13'' mbp it really hits performance hard especially when using two external monitors vim/terminal is not fun at all!

I am constantly restarting  the process and I slowed down tmux refresh interval but let's be honest that's not a solution at all, even with constant restarting I have quite a lot of lag especially using vim but at least it is somewhat usable compared to not restarting the process all the time.

**Comment by vinc386** [comment]
@joshperry how did you do that? I tried: 

    sudo kill -SIGTERM `ps -A | grep notifyd`
but `notifyd` just kept respawning itself…

**Comment by schaefer-dev** [comment]
@vinc386 
`alias bug="sudo kill $(ps aux | grep '[n]otifyd' | awk '{print $2}')`
thats what I am using and its working just fine. respawning is totally intended, but it fixes the lag for some time at least

**Comment by adambiggs** [comment]
I noticed that when I have an active Tmux session, the `notifyd` process is flooded with thousands of context switches and faults per second, and seems to consume more and more memory.

But after killing all Tmux sessions, this behaviour stops.

> You all need to stop telling me about this and go and tell Apple.

I totally get that Apple is most likely at fault here. But as @wincent said, given the severity of this problem, *anything* that can be done on the Tmux end to mitigate it would be much better than blindly waiting for a fix from Apple.

**Comment by schaefer-dev** [comment]
@adambiggs
Does killing all Tmux sessions really helps you? As soon as I start tmux again the error will occur and killing tmux helps just as much as restarting notifyd. Is this different for you?

The problem with Apple being at fault here is that it will probably take really long for them to fix this and to be honest my workflow is pretty f***ed up now after the update but I can't just stop using tmux.

**Comment by vinc386** [comment]
@schaefer-dev thanks! Will give that a try next time I run into this bug

**Comment by adambiggs** [comment]
@schaefer-dev killing Tmux sessions only stops the flood of context switches and faults in `notifyd`. It doesn't fix anything. I just mentioned this because, for me at least, it seems the problem is limited to Tmux. `notifyd` doesn't show this behaviour on it's own.

**Comment by zacharyvoase** [comment]
At the very least I've reported this to Apple. I'm interested to know why it happens and might try to develop a patch for tmux, but I can't make any promises :-)

**Comment by wincent** [comment]
@schaefer-dev 
> where can you report this error to apple?

You can report it [bugreport.apple.com](https://bugreport.apple.com/). Generally, the more reports the merrier; Apple uses the number of reports to prioritize their efforts.

**Comment by diversario** [comment]
Filed a bug with them (22980503).

**Comment by dphaener** [comment]
:+1: Also filed a bug (22980745)

**Comment by joshperry** [comment]
Thanks for filing the bug guys. Now to find a better workaround :)

**Comment by rrva** [comment]
I think 

set -g status off

works for me. However, i've also upgraded OSX to 15B22c and ITerm2 to 2.1.3

Did anyone capture anything useful by running notifyd with -d ?

**Comment by frbl** [comment]
+1, filled a bug (22986668)

**Comment by leyyinad** [comment]
Thank you very, very, very much rrva,

    set -g status off

does it for me. Saved my life.

**Comment by schaefer-dev** [comment]
@leyyinad yeah its fixing the problem but you don't have any statusbar anymore which kinda sucks

**Comment by craigp** [comment]
FWIW I did notice in the changelog for the iTerm update this morning (2.1.4) that a bug had been fixed with tmux integration which caused tmux to exit with an error code..

**Comment by schaefer-dev** [comment]
@craigp is this the bug we are talking about? I am on 2.9.20151001 beta and I got no update

**Comment by craigp** [comment]
@schaefer-dev nope, whatever iTerm did, it doesn't help, just had to hard boot my machine after killing tmux. I'm going to try disabling the status line as above.

**Comment by craigp** [comment]
All hail @rrva .. works great, can finally use tmux again, and can live without a status line for now :+1:

**Comment by nicm** [comment]
Try adding "return NULL;" as the first line of both osdep_get_name and osdep_get_cwd in osdep-darwin.c and rebuilding tmux.

**Comment by anugupta** [comment]
I'm using byobu, with a tmux backend, and have had the same issues.

My temporary solution is to remove all the notifications on the status bar, but not turn it off. Seems to be working very well so far - I can live without the monitoring, but I still get to see my windows.

**Comment by drselump14** [comment]
I'm using tmux-powerline + iTerm2 and experienced the same issue (high cpu resource and slow typing) ... 
Disabling powerline segment which require osascript (weather, now playing) seems solved the problem in my case ...

**Comment by drselump14** [comment]
And mac freezes after quit tmux :( 
at least I can do my job on tmux for several hours without losing the status bar

**Comment by jaredbonobos** [comment]
Im glad i wasn't going crazy. Turning the status bar off would make me feel like I'm blind out of one eye. Has anyone heard back anything?

**Comment by dphaener** [comment]
From earlier conversations, killing notifyd will resolve the laginess and high cpu usage, though it will come back again. Still no good resolution for freezing other than quitting iterm without killing tmux and rebooting.

**Comment by schaefer-dev** [comment]
@drselump14 I think you hit the nail! I disabled everything using oascript and so far its working perfectly fine!

**Comment by tomphp** [comment]
+1 - same problem here

**Comment by schaefer-dev** [comment]
> Disabling powerline segment which require osascript (weather, now playing)
> - @drselump14 
I used it for 4 hours now and It's perfectly stable just like it was in Yosemite. This is by far the least bad workaround for me and I can absolutely live with avoiding oascript until this is fixed on apples side.

**Comment by gfontenot** [comment]
fwiw, that's not actually a fix. I'm not using any osascript (or iTerm, or powerline) and I'm seeing the same issues.

**Comment by schaefer-dev** [comment]
@gfontenot Thats pretty strange! Can you give some details what you are using and when/how the problem occurs?

**Comment by gfontenot** [comment]
Exact same issues, notifyd gets out of control, killing it helps for a while, etc. Not using any crazy tmux plugins. Using Terminal.app instead of iTerm. Etc, etc. Status bar only has a couple of simple shell scripts running, no osascript to be found.

**Comment by schaefer-dev** [comment]
@gfontenot Maybe you can get it 'working' with iTerm and/or without the scripts. Might be worth a try and I would at least kill notifyd in between or maybe even restart. On my other machine just disabling osascript didn't work immediately I had to restart for some reason.

**Comment by gfontenot** [comment]
Thanks, but I'm not going to do that. Killing `notifyd` a few times a day is letting me get my work done and I'll keep watching this thread for an actual fix.

**Comment by tupton** [comment]
Turning the status bar off is a non-starter for a lot of people, but it seems that turning status bar *updates* off is also a fix. Some people have increased the interval of updates; I'm curious to know if that has actually fixed the problem or if it has just caused `notifyd` to have less context switches.

Turning off status updates seems to have fixed it for me. I've been running a tmux session for a couple of hours and I just exited it with no problem.

From the [man page][man-tmux]:

> status-interval interval
>                     Update the status bar every interval seconds.  By
>                     default, updates will occur every 15 seconds.  A setting
>                     of zero disables redrawing at interval.

  [man-tmux]: http://manpages.ubuntu.com/manpages/precise/en/man1/tmux.1.html

So the following in `tmux.conf`has done the trick for me. I still have `automatic-rename` and `allow-rename` on and it seems to be fine.

```
set -g status-interval 0
```

**Comment by Atcold** [comment]
+2 (me and my colleague).

**Comment by leyyinad** [comment]
Make sure to pay attention to installed tmux plugins as well. I found *tmux-continuum* is using `osascript` eg.

**Comment by chgu82837** [comment]
I got this error too... looking for updates :unamused: 
currently use `set -g status-interval 0` for the quick fix.

**Comment by drselump14** [comment]
For AppTamer users, start from version 2.1.0 you can slow down `notifyd` process if it uses a lot of CPU resources ....

![App Tamer Download](http://t.co/NeOhvrvPnq)

![About App Tamer](http://www.stclairsoft.com/AppTamer/)

**Comment by kthelgason** [comment]
@nicm Tried returning `NULL` as you suggested. Been running all day with no problems.

**Comment by ericboehs** [comment]
Has anyone else confirmed the `NULL` patch?

**Comment by jdmonaco** [comment]
@ericboehs Running it for a couple hours. Notifyd has crept up to about 8-15% usage after two hours. This is happening even after disabling status updates and removing the updated powerline segments. I'm keeping an eye on it, but I'm not sure the patch solved the problem. (Side effect:  new windows are named 'reattach-to-user-namespace' (my default program setting) instead of 'bash'.)

**Comment by joshperry** [comment]
The NULL patch seems to be working for me, been working for a few hours now and notifyd hasn't increased in CPU.

This isn't a great long term solution, it just removes platform detection for OSX, effectively bypassing OSX-specific code paths and tmux's OSX features along with it.

A number of my powerline segments are bunk, but at least I don't have to kill notifyd 10 times a day...

**Comment by adambiggs** [comment]
The NULL patch seems to have fixed this for me as well.

I'm not sure if this is just a breaking change in Tmux v2.1, but I noticed that when using the patched version `pane_current_command` doesn't seem to work as expected anymore.

If a pane is running Vim, and I run `display-message -p '#{pane_current_command}'` in the Tmux command prompt, it prints `zsh` where previously it would be `vim`. This has broken [`vim-tmux-navigator`](github.com/christoomey/vim-tmux-navigator/issues/84). But disregard this if it's an unrelated issue.

**Comment by joshperry** [comment]
@adambiggs Your issue is the same as the side-effects @jdmonaco mentioned. This is most likely caused by some OSX-specific code for finding the name of the command executing in the current shell being bypassed by the NULL patch.

**Comment by adambiggs** [comment]
Ah that makes sense.

**Comment by atav32** [comment]
@tupton +1 `set -g status-interval 0` is a quick fix

**Comment by jdmonaco** [comment]
Disregard my previous unsureness about the NULL patch, I think I had a shell hash somewhere holding onto the unpatched tmux. Going on 6 hours now after rebooting with notifyd <0.2%.

**Comment by victorcoder** [comment]
+1 `set -g status-interval 0` fixes it

**Comment by rrva** [comment]
What bothers me is we do not understand why notifyd starts spinning. Also, without tampering too much I cannot dtrace notifyd to inspect what it is doing. Anyone did that? Clearly, as stated at the very top this is probably not a tmux issue. Still github is a nice place to discuss it. Also here:

https://forums.developer.apple.com/thread/9753

**Comment by jdmonaco** [comment]
Apple just closed my bug report (#22966009) as a duplicate (#22978376), so this may be getting noticed.

**Comment by dphaener** [comment]
:+1: mine too, as a duplicate of the same one.

**Comment by joshperry** [comment]
@rrva I have been trying to trace the culprit down. I got notifyd to run in debug log mode. Seeing some interesting behavior.

Every couple seconds (whatever your status bar refresh rate is) there is a stream of these:

![image](https://cloud.githubusercontent.com/assets/298053/10406912/81509484-6ea1-11e5-9f03-69f2765e26d4.png)

The number at the end increments serially, the one previous to that is the PID.

After a while this list grows to hundreds every couple seconds, at the same time notifyd grows in both CPU _and_ memory. What I think is happening, is some API that is being used by tmux is causing subscriptions for message notifications from notifyd to never be released.

If you kill tmux before this list gets too large, there is no system lockup. If you wait until notifyd is well-loaded, then kill tmux, the system locks up. I think this freeze up may be because of trying to release an immense number of OS level resources (mach ports?) all at the same time as the tmux process terminates.

This is a pretty effective user-mode DoS attack.

Last I had a little time to work on it, I tried to connect with lldb, break on the [function that log message is from](http://www.opensource.apple.com/source/notify/notify-25/notifyd.tproj/notify_proc.c), and get a stack trace to see if we could find the API and work around the problem. But I got this instead and haven't had time to work on it anymore: 

![image](https://cloud.githubusercontent.com/assets/298053/10406901/6cb00c26-6ea1-11e5-9a1e-3cabf5808a73.png)

**Comment by wlhlm** [comment]
@rrva, @joshperry El Capitan introduced [SIP](https://en.wikipedia.org/wiki/System_Integrity_Protection) which prevents processes from  tampering/modifying memory of processes that are signed with Apple's private key. That means you are no longer able to attach a debugger to applications that are part of the base operating system. Even root can't circumvent that.

**Comment by diversario** [comment]
@wlhlm You can disable it temporarily – http://lifehacker.com/how-to-fix-os-x-el-capitans-annoyances-1733836821

**Comment by kthelgason** [comment]
I also see what @joshperry described, however the entire OS becomes unresponsive when I try to attach an lldb session to `notifyd`. Is there a chance that this issue is in libevent? Has anyone noticed similar problem in other software built on libevent?

**Comment by hiberabyss** [comment]
Since kill `notifyd` work for me, I write a cron job which kills  `notifyd` each hour.
Save this as a file name `killnotifyd.cron`,
```
30 * * * * pkill notifyd
```
then use `sudo crontab /path/to/killnotifyd.cron` to add a cron job.

You can use `sudo crontab -l` to verify whether it's added correctly.

**Comment by kthelgason** [comment]
There are lots of workarounds posted here, but has anyone gone any further in trying to dig up the cause? It looks to me like this might legitimately be a tmux issue.

**Comment by nicknisi** [comment]
I am also suspicious that this is a tmux issue. However, the workaround that is working for me is updating  to the latest HEAD (2.1) for  tmux. I install tmux through homebrew, so I did `brew reinstall --HEAD tmux` and I have not seen the issue since.

**Comment by joshperry** [comment]
I've tried, but I'm stuck at finding debug symbols for notifyd. If I can't break on the function that's registering the handlers, I can't follow the stack trace back up to tmux and see which API calls are actually causing the issue.

I'm just not strong enough at really low level reversing to track this down myself :/ Sorry.

I've ditched tmux and went back to using iTerm2 tabs for now. I've always used window splitting in vim, so that's not a big loss for me.

In the process I have somehow even broken my notifyd and now things in OSX are going wonky, like Calendar crashing on open, and my battery level and charge indicator frozen in time.

![image](https://cloud.githubusercontent.com/assets/298053/10491181/713c7e18-7262-11e5-848e-b6b3fc3f7bf7.png)

**Comment by joshperry** [comment]
@wlhlm @rrva @kthelgason I disabled SIP and was able to attach lldb using the launchctl command. When you first attach, lldb will halt the process you've attached to, so you have to do `continue` for notifyd to keep doing its thing.

Like I referenced in my previous post, without debug symbols for notifyd I'm not sure exactly how to track down the issue.

**Comment by joshperry** [comment]
@nicknisi Interesting, perhaps diffing HEAD with the release rev and looking at changes in the OSX-specific code could give us some clues.

**Comment by joshperry** [comment]
I'm sure you have unsubbed, @nicm. But this issue seems to be fixed when building from master. Perhaps you wouldn't mind taking a quick look? Considering your familiarity with the source, any help would be really appreciated.

**Comment by nicm** [comment]
We redraw the status line and fire the proc_pidinfo code a lot less often in master. The bug is not gone, it is not a bug in tmux, but we are probably no longer triggering it (or are doing so much more rarely).

**Comment by joshperry** [comment]
@nicm thank you for the additional info, definitely makes sense. @nicknisi would you mind updating us in a day or so with info on if your notifyd process is slowly growing in memory and proc even in the smallest manner

**Comment by rrva** [comment]
dtrace instead of lldb or just run xcode instruments to get a highlevel
view of whats happening when notifyd eats cpu
Den 14 okt. 2015 9:12 em skrev "Joshua Perry" <notifications@github.com>:

**Comment by nicknisi** [comment]
@joshperry I haven't noticed any issues in the couple of days I've been running it. Before, when I would disconnect from tmux, the Mac would freeze within a few seconds. So far, no issues.

**Comment by pengux** [comment]
One issue with using HEAD is that there's no true color support :-(

**Comment by ThomasAdam** [comment]
@pengux - that has nothing to do with this issue, and is being worked on by someone anyway.

**Comment by simonsmith** [comment]
Just to add, I've had `status-interval` set to `0` for a couple days (no restart of tmux, just sleeping Mac) and I still got the crash when killing the tmux server. 

Will try installing from master too

**Comment by tupton** [comment]
> Just to add, I've had `status-interval` set to 0 for a couple days (no restart of tmux, just sleeping Mac) and I still got the crash when killing the tmux server.

I've been running tmux for a number of days, too, and I just tried exiting. It took a lot longer than usual, but there was no hang or crash, and it eventually exited normally.

Not ideal, to be sure, but I didn't experience a crash or system-wide hang.

**Comment by adambiggs** [comment]
Thanks @hiberabyss, the cron job you posted is probably the best workaround anyone's suggested so far.

**Comment by felipecabargas** [comment]
Hey guys, I had the same problem and thought it was tmux (used the hotfix above, etc) ... Finally I came across a solution much more simple than that: Update the holly command line tools

`xcode-select --install`

Here I am, hours after with 2 macs running tmux/zsh sessions (and using them) and `notifyd` stays at 0%. I guess that "El Capitan" and the Xcode 7.1 Update itself didn't updated the notify API so we got the errors. 

My 2 macs in case it helps:
- MacBook Air 13.3" mid-2013, El Capitan 10.11.1 beta 4
- Mac Mini late-2012, El Capitan 10.11 Final Release

**Comment by kthelgason** [comment]
@felipecabargas Can you report on the version of `clang` you have installed? I still see the same behaviour in the logs as reported above, with a `register_check` for `com.apple.system.timezone` each update interval. Will leave tmux running for a while to see if `notifyd` starts misbehaving. It's possible though that I misidentified the problem to begin with and those log messages are completely unrelated.

**Comment by felipecabargas** [comment]
@kthelgason 

```
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
```

**Comment by joshperry** [comment]
@felipecabargas I am unable to reproduce your results. I have the same tool revs as I just updated to the El Capitan toolchain a couple days ago, rebuilt tmux and tmux pasteboard and am still getting notifyd issues. Perhaps I should try rebuilding my whole stack to see if a tmux dependency is a culprit.

**Comment by kiyanwang** [comment]
`set -g status-interval 0` seems to have resolved the issue for me (at least for now)

**Comment by evserykh** [comment]
```set -g status-interval 0``` doesn't help me

After exiting all Tmux's sessions and quiting Terminal.app OS freezes for few minutes. It works as usually after that

* El Capitan
* Terminal.app
* Tmux 2.0
* Command Line Tools 7.0

**Comment by simonsmith** [comment]
The previous comment about using master has seen the issue disappear for me. Am now using `2.1` without any issues so far.

**Comment by gfZeng** [comment]
@simonsmith

I'm now use tmux 2.0, I am `set-option -g status off`, that works fine to me.
can I `set-option -g status on` on tmux 2.1.

**Comment by simonsmith** [comment]
Do you mean `status-interval`? I've set that back to `5` and have been without issue

**Comment by gfZeng** [comment]
@simonsmith I'm not open status now. I will try reopen status. thank you

**Comment by rob-anderson** [comment]
xcode-select install
brew upgrade tmux (2.1)

worked for me.

Notifyd is back in its box chewing 0.2% cpu and my powerline bar is updating normally.

**Comment by Hywan** [comment]
Filled a bug on bugreport.apple.com too (23198918).

**Comment by kthelgason** [comment]
I have updated to the newest version of devtools and tmux 2.1 and I can report that the issue has definitely not been resolved. As @nicm points out above it just takes longer to bog down `notifyd`. I just shut down a long-running (4 days) tmux session and had the mac crash.

**Comment by kthelgason** [comment]
From the console logs it looks like the update to 10.11.1 fixed this issue. Anyone else seeing the same?

**Comment by tbjers** [comment]
@kthelgason I just installed 10.11.1 and I am not seeing a freeze after quitting Tmux, however, I tested with set -g status-interval 0, I am going to set it back down to every second to see how that affects things. By the way, 1s interval worked fine in Yosemite.

**Comment by mschae** [comment]
I am afraid this is still an issue: It didn't freeze my entire Mac OS (as it did before) but I still saw notifyd at 100% when waking my MacBook this morning.

I didn't do a new `xcode-select --install` after the upgrade yesterday so maybe that step was missing.

Thanks everyone on this for narrowing down what's happening. Was driving me insane the last few weeks.

**Comment by tbjers** [comment]
I did an `xcode-select --install` last night after upgrading to 10.11.1 and set my `tmux.conf` back to whatever it was before I started trying to narrow down what was going on.

I left my MacBook Air on all night with five open tmux tabs, one running Ionic, one running Rails/Puma, and one running a MongoDB instance, then I got to work this morning.

I just quit tmux as a test and it didn't cause any of the previous issues!

**Comment by kthelgason** [comment]
I'm still a little bothered by having no idea what was causing the issue in the first place, but I guess I'll get over it given some time!

**Comment by russmatney** [comment]
I had these symptoms on two machines for too long and it was making me crazy - read through this thread yesterday, and then I: 

- updated to 10.11.1
- ran an `xcode-select --install`
- upgraded tmux to 2.1 (with true-color via [choppsv1/homebrew-term24](https://github.com/choppsv1/homebrew-term24) @pengux if you're still looking.)

Happy to report that everything is back to normal through a few hours of work yesterday and a full day today – `notifyd` never gets above 0.2% cpu. Hope the same for the rest of you!

**Comment by Starefossen** [comment]
Mac OS X 10.11.1 and tmux v2.1 seamed to do the trick for me. 

`xcode-select --install` yields the following for me though: 

```
$ xcode-select --install
> xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by artursapek** [comment]
I'm happy to confirm that updating to OS X 10.11.1 and tmux 2.0 helped fix this annoying problem. `notifyd` doesn't rise above 2% CPU anymore, whereas before it would regularly climb to anywhere between 10 and 90% CPU. This had been bothering me for weeks. tmux/vim combo should be fast! That's the point!

**Comment by drn** [comment]
I have been lurking on this (and other threads) about issues with a slow tmux environment after upgrading to El Capitan. None of the before-mentioned fixes solved the slowness, so thought I should share.

Disabling the status line made it somewhat better, but didn't completely solve the lag. I noticed that the `fontd` process spiked while I was getting lag in tmux. I checked my iTerm2 config and for some reason after the El Capitan upgrade, the "Regular Font" and "Non-ASCII Font" settings changed from my regular "Menlo Regular for Powerline" to "Monaco". Because I was using powerline symbols in my status line / prompt, I suspect that `fontd` was trying to search for an acceptable fallback every time the character was used. Switching it back to "Menlo Regular for Powerline" has solved my slow environment.

Hope this helps someone.

**Comment by Atcold** [comment]
@drn, I think you're completely out of topic here. This thread is about *El Capitan* freezing when *tmux* is exited.

**Comment by carlitux** [comment]
As @artursapek with OS X and tmux updates this looks like is fixed...

**Comment by drn** [comment]
@Atcold - Fair enough, but to an extent.

The lag due to the increased CPU load caused my entire machine to hang. This was related to the second issue reported by the issue reporter "Additionally, Vim and Terminal apps start becoming sluggish and unresponsive after a session is open for a day or two."

Yes, likely a completely separate issue. However, any tmux users running into "tmux lag in el capitan" would definitely run into this thread and could potentially benefit from my use case.

Glad the original issue is fixed.

**Comment by kthelgason** [comment]
@drn not a separate issue, this is exactly what I was experiencing. As discussed above it's is now fixed.

**Comment by maxjacobson** [comment]
I've been following this thread because I've been experiencing some tmux freezes since upgrading to El Capitan. I'm using the latest tmux from Homebrew and still seeing the issue. Where was it fixed?

**Comment by dphaener** [comment]
@maxjacobson I had to upgrade to OS X 10.11.1 and Tmux 2.0 to get it to completely stop. For me, it has resolved both issues (the freezing and the laginess).

**Comment by diversario** [comment]
For me, running tmux 2.1 and OS X 10.11.1 still hasn't resolved it. I cannot set `status-interval` below 10 or turn on `visual-activity` without tmux eventually killing my machine.

**Comment by fuadsaud** [comment]
Updating to OS X 10.11.1 and Tmux HEAD has also fixed it for me.

On Thu, Nov 5, 2015 at 2:15 PM Darin Haener <notifications@github.com>
wrote:

> @maxjacobson <https://github.com/maxjacobson> I had to upgrade to OS X
> 10.11.1 and Tmux 2.0 to get it to completely stop. For me, it has resolved
> both issues (the freezing and the laginess).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tmux/tmux/issues/108#issuecomment-154108428>.
>
-- 
Fuad Saud

http://fuad.im • https://www.linkedin.com/in/fuadsaud

**Comment by maxjacobson** [comment]
I'm using OS X 10.11.1 and tmux 2.1 (latest from Homebrew). When you say HEAD, does it mean you've had to build it manually from source? I'll try :sweat_smile:

**Comment by fuadsaud** [comment]
@maxjacobson `brew install --HEAD tmux` :) That'll pull down tmux 2.2 source (from git master) and build it.

**Comment by maxjacobson** [comment]
@fuadsaud aha thanks :whale2:

**Comment by timhtheos** [comment]
+1 Subscribing.

**Comment by filipeamoreira** [comment]
+1

**Comment by dmuth** [comment]
Just to throw in my 2 cents, here what was I had going on:
- OS/X 10.11, which was upgraded from 10.10, which had previously been upgraded from 10.8(?) which came with this iMac nearly 3 years ago
- Tmux 1.9a
- Latest version of Homebrew

The problem I was having is that tmux was slowing down when I ran Ansible 1.8.4 against a VM in Vagrant.  Whenever I ran Ansible, tmux would slow to a crawl while Ansible was running in the same window. (that is, my adjacent pane would slow down by a lot)

As per some of the suggestions here, I killed the notifyd process and that *instantly* fixed the problem.  A new notifyd was restarted, but tmux now behaved normally.

-- Doug

**Comment by artursapek** [comment]
I have some more fun info to share. Last night, still frustrated with this problem, I tried what [this reddit user suggested](https://www.reddit.com/r/applehelp/comments/3lff0o/anyone_know_why_notifyd_is_taking_up_so_much_cpu/cwh1qn4). In retrospect, I should have just set tmux's `status-interval` to `0` and been happy with that, but I was being stubborn and thought "I never use notification center anyway, so this sounds like a good idea".

About 10 minutes after `unload`ing `notifyd` I tried restarting my laptop to start a fresh session, and to my horror the login screen would slow to a crawl at around 75% progress, slowly inch forward to a full 100%, and then *never finish*. It would just sit indefinitely at 100%, taunting me. I waited 10-20 minutes. I can't imagine why it would have finally gone through after that long. It was clearly just broken.

I restarted probably a dozen times, and reproduced every time.

I'm pretty certain this was caused by my turning off notifyd. I had successfully restarted a few days prior to this.

The next thing I tried was reinstalling El Capitan from recovery mode, but the same issue persisted after the fresh install. This was kind of confounding.

My next idea was to downgrade to Yosemite from a USB because I preferred it anyway. Unfortunately every blog post I could find about it online mentioned downloading the installer from the App Store, where it's no longer available. I couldn't find it anywhere else on the net, either. Apple clearly wants people to stay on El Capitan.

After a very frustrating evening, I ended up running an overnight tar backup of my home directory to an external disk. Then, this morning, I booted into recovery mode and wiped Macintosh HD. When I rebooted again, the machine went straight into NetBoot mode and miraculously decided to install Yosemite instead of El Capitan! This made sense, because it was the OS my machine shipped with (early 2015 MBAir). There's clearly still some Apple machines out there serving Yosemite up to broken machines like mine.

That install went quickly and smoothly, and after I extracted my home directory back onto the machine I only have a couple hours of re-installing and re-configuring left ahead of me. Very happy ending, if you ask me. I'm glad to be rid of El Capitan and its `notifyd`/`kernel_task` bullshit. What a racket.

**Comment by stixpjr** [comment]
AFAICT, this might be fixed with 10.11.2... I've been running until now with "/usr/bin/pkill notifyd" 15 minute cron job workaround, and I've noticed notifyd spiking CPU usage frequently. After installing 10.11.2, I've disabled the cronjob and notifyd CPU usage is negligible after reasonably heavy tmux use. Maybe Apple silently fixed it?

**Comment by chestarss** [comment]
+1 same problem

**Comment by kthelgason** [comment]
@chestarss have you read and tried any of the solutions in this thread?

**Comment by chestarss** [comment]
@kthelgason i am tring "set -g status-interval 0"

**Comment by kthelgason** [comment]
Are you not able to update to 10.11.2 or newer?

Sent from my iPhone




On Tue, Apr 19, 2016 at 4:11 AM -0700, "chestar" <notifications@github.com> wrote:












@kthelgason i am tring "set -g status-interval 0"

**Comment by chestarss** [comment]
my os version is 10.11 now, i will update it to 10.11.4

**Comment by chestarss** [comment]
@kthelgason my english is so poor, the above answer may not recognise
