### ISSUE TITLE
tmux crashes each night

### ISSUE THREAD

**Issue by newellista** [tmux/tmux#184]
I am running tmux on Mac OS X 10.11.1 in iTerm 2.1.4.

Each morning, when I come back in, tmux has exited.  I have looked for core dumps, but can't find any.  What information can I gather that will help troubleshoot this issue?

Thanks!

**Comment by nicm** [comment]
Are you sure it has actually exited and not just the socket has been removed?

Attach to the tmux server with gdb in the evening and then the next day gdb should show what has happened:

$ pgrep -lf tmux
22896 tmux: server (/tmp/tmux-1000/test)
$ gdb -q tmux 22896
Attaching to program: /usr/bin/tmux, process 22896
...
(gdb) c
Continuing.

**Comment by hojberg** [comment]
This happens for me also! Same specs as @newellista 
Thank god for this issue, I thought it was going insane lol.

**Comment by hojberg** [comment]
I'll try what @nicm suggests tonight

**Comment by newellista** [comment]
tmux was definitely exiting.  The process was not running in the morning. 

I did a little more experimenting, and found that if I removed [tmux-mem-cpu-load](https://github.com/thewtex/tmux-mem-cpu-load), the crashes stopped.

Since that was not critical to my workflow, I simply removed the plugin, but didn't investigate further.

**Comment by DuBistKomisch** [comment]
I have the same issue, on the same versions as @newellista, and the process is nowhere to be found. I go to iTerm in the morning and it just says `[server exited]`. It was working fine until yesterday morning for me, but I just assumed it was because I hadn't touched my laptop the whole weekend, then it happened again this morning so I started googling and ended up here.

I never had tmux-mem-cpu-load installed, but I did recently switch back to bash from zsh, so there could be some weird configuration causing it. I'll try reinstalling tmux through homebrew, then if it happens again tomorrow, attaching gdb at the end of the day.

**Comment by DuBistKomisch** [comment]
Apparently reinstalling upgraded it from 2.0 to 2.1 (not sure why it didn't get upgraded when running `brew upgrade`...). Didn't happen again last night so seems like it's fixed in 2.1.

**Comment by rohanorton** [comment]
I still have this issue in version 2.1. It seems to crash after laptop has gone into deeper sleep (i.e. if I don't use it for ~12hr and it's unplugged). I don't use tmux-mem-cpu-load plugin, though I do use powerline and zsh, not sure if that is relevant.

```bash
$ gdb -q tmux 3198
Reading symbols from tmux...(no debugging symbols found)...done.
Attaching to program: /usr/local/bin/tmux, process 3198
0x00007fff90c8a222 in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
(gdb) continue
Continuing.
[Inferior 1 (process 3198) exited normally]
(gdb)
```

**Comment by nicm** [comment]
If it is exiting normally, possibly it is fatal()ing. Run tmux -v new then after it exits, check the tmux-server-*.log file in the directory where you started tmux, and see if the last couple of lines show a fatal error.

**Comment by rohanorton** [comment]
It had exited again this morning. No fatal error that I can see. Here's the last 100 lines 

```bash
$ tail -n 50 tmux-server-*.log
1448355030.762724 continuing cmdq 0x7fb870d731d0: flags=0, client=55
1448355030.762738 cmdq 0x7fb870d731d0: display-message -p 272
1448355030.762763 writing 211 to client 55
1448355030.762778 cmd_find_pane: target none (failed)
1448355030.762871 event dispatch exit
1448355030.762882 writing 203 to client 55
1448355030.762892 event dispatch enter
1448355030.762939 lost client 55
1448355030.763061 unref client 55 (1 references)
1448355030.763147 got 205 from client 7
1448355030.773295 writing 204 to client 7
1448355030.773316 got 205 from client 7
1448355030.773324 writing 204 to client 7
1448355030.773332 got 205 from client 7
1448355030.773338 writing 204 to client 7
1448355030.773344 got 205 from client 7
1448355030.773348 writing 204 to client 7
1448355030.773355 event dispatch exit
1448355030.773361 event dispatch enter
1448355030.773586 got 205 from client 11
1448355030.773733 writing 204 to client 11
1448355030.773745 got 205 from client 11
1448355030.773753 writing 204 to client 11
1448355030.773761 got 205 from client 11
1448355030.773768 writing 204 to client 11
1448355030.773775 got 205 from client 11
1448355030.773781 writing 204 to client 11
1448355030.773793 free client 55 (0 references)
1448355030.773800 event dispatch exit
1448355030.773807 event dispatch enter
1448355030.773865 event dispatch exit
1448355030.773874 event dispatch enter
1448355030.774069 event dispatch exit
1448355030.774080 event dispatch enter
1448355030.774164 event dispatch exit
1448355030.774175 event dispatch enter
1448355030.774500 event dispatch exit
1448355030.774513 event dispatch enter
1448355030.774604 event dispatch exit
1448355030.774614 event dispatch enter
1448355030.775262 lost client 11
1448355030.775324 unref client 11 (1 references)
1448355030.775335 event dispatch exit
1448355030.775345 event dispatch enter
1448355030.775368 free client 11 (0 references)
1448355030.775378 event dispatch exit
1448355030.775387 event dispatch enter
1448355030.779715 lost client 7
1448355030.779909 unref client 7 (1 references)
1448355030.779925 event dispatch exit
```

**Comment by nicm** [comment]
Send me the full log please.

**Comment by rohanorton** [comment]
Um... the full log is 2.8 gigabytes

**Comment by nicm** [comment]
give me the last 100000 lines then, and gzip it

**Comment by nicm** [comment]
Email it if you have typed any passwords in the log

**Comment by nicm** [comment]
Something sent your tmux server a SIGTERM and so it exited, you should find out what is doing that.

**Comment by nicm** [comment]
In fact, it sent it four times. This is message 210, which is MSG_SHUTDOWN, which is only sent on TERM, so either something is sending TERM to tmux or it is doing "tmux kill-server", I'd guess probably the former.

1448355029 is 08:50:29 GMT.

1448355029.536199 writing 210 to client 7
1448355029.536206 writing 210 to client 11
1448355029.536213 writing 210 to client 55
1448355029.536218 session 0 destroyed
1448355029.536226 session 0 has 2 references
1448355029.562235 session 0 has 2 references
1448355029.617861 session 0 has 2 references
1448355029.728395 session 0 has 2 references
1448355030.115397 session 0 has 1 references
1448355030.115418 session 1 destroyed
1448355030.115427 session 1 has 2 references
1448355030.115440 session 1 has 2 references
1448355030.337622 session 1 has 2 references
1448355030.490729 session 1 has 2 references
1448355030.491066 session 1 has 2 references
1448355030.732807 session 1 has 1 references
1448355030.732822 writing 210 to client 7
1448355030.732829 writing 210 to client 11
1448355030.732835 writing 210 to client 55
1448355030.732840 writing 210 to client 7
1448355030.732844 writing 210 to client 11
1448355030.732849 writing 210 to client 55
1448355030.732854 writing 210 to client 7
1448355030.732858 writing 210 to client 11
1448355030.732863 writing 210 to client 55

**Comment by rohanorton** [comment]
Weird. Thanks, I'll have a dig about and see what the culprit is.
