### ISSUE TITLE
C-b keeps taking commands for too long

### ISSUE THREAD

**Issue by mathieulongtin** [tmux/tmux#203]
If I type this:
```
<C-b><right-arrow>cd<space>/some/directory
```
until 2.1, this would move the cursor one pane to the right and start typing the change directory command. Since 2.1, it moves the cursor one pane to the right and then creates a new window continaing:
```
d /some/directory
```
Before, the C-b would only chain pane movements, but now it chains everything.

Is there a way to stop that?

**Comment by nicm** [comment]
Pretty sure this is fixed in git.

**Comment by marcaddeo** [comment]
I think I'm getting a similar problem.

When I try and resize my panes with my hotkeys it will switch to the previous window if I type to fast. This wasn't the case before.

For instance if I quickly type `C-a j` `C-a j` to resize my pane, it will switch to my previous window (`C-a C-a`)

**Comment by mathieulongtin** [comment]
Just compiled github version and the bug is still there.

BTW, on CentOS 6.6, `__unused` screws up `bits/stats.h` when compiling `compat/closefrom.c`:
```
/usr/include/bits/stat.h:106: error: expected identifier or ‘(’ before ‘[’ token
```

To fix: in compat/closefrom.c, move `#include "tmux.h"` after the system includes.

**Comment by nicm** [comment]
All the same, I am pretty sure I fixed this and I can't reproduce it with the description you gave. Please make sure you are actually running a build from master (kill tmux entirely etc) then provide exact instructions on how to reproduce.

**Comment by mathieulongtin** [comment]
Compile latest from github master (except for above include fix), remove ~/.tmux.conf to make sure it's not in the way, then run with: `./tmux new-session`

C-b%   (split window)
C-b<leftarrow>cd

It moves to the left pane then creates a new window and types d in the new window. I would expect to move to left pane then type "cd".

This is CentOS release 6.6 (Final).

**Comment by nicm** [comment]
C-b c creates a new window, this is working as intended.

**Comment by mathieulongtin** [comment]
\<leftarrow\> got swallowed the first time around... didn't quote properly.

**Comment by nicm** [comment]
This works for me. Show me the output of this from /inside/ tmux please:

       /proc/$(tmux display -p '#{pid}')/exe -V

**Comment by mathieulongtin** [comment]
Nevermind. I hadn't quit the already running tmux server, and `tmux new-session` was using it. I assumed a new-session gave a separate server.
