### ISSUE TITLE
select-word in first line makes the screen scrolls up

### ISSUE THREAD

**Issue by ofdeath** [tmux/tmux#2393]
### Issue description

select-word command (by DoubleClick on any shell) in the first line of screen always makes the screen scrolls up - one or several lines.
I thinks below code makes the problem

window_copy_start_drag in window-copy.c
```
                  case SEL_WORD:
                          if (data->ws) {
                                  window_copy_update_cursor(wme, x, y);
                                  window_copy_cursor_previous_word_pos(wme,
                                      data->ws, 0, &x, &y);
                                  y -= screen_hsize(data->backing) - data->oy;
                          }
                          window_copy_update_cursor(wme, x, y);
                          break;
```

Because above code updates data->cx and data->cy and the function window_copy_cursor_up is always called in below code.

window_copy_drag_update in window-copy.c
```
          if (old_cy != data->cy || old_cx == data->cx) {
                  if (y == 0) {
                          evtimer_add(&data->dragtimer, &tv);
                          window_copy_cursor_up(wme, 1);
                  }
```

Do you think this problem is caused by above reason?

### Required information

Please provide the following information:

* tmux version (`tmux -V`).
3.1b with below commit

```
    Correctly move to previous line when looking for previous word, from
    Derry Jing.
---
 window-copy.c | 9 ++++-----
 1 file changed, 4 insertions(+), 5 deletions(-)

diff --git a/window-copy.c b/window-copy.c
index 2a47e9b..3a0ec4c 100644
--- a/window-copy.c
+++ b/window-copy.c
@@ -4115,15 +4115,14 @@ window_copy_cursor_previous_word_pos(struct window_mode_entry *wme,
                                    separators))
                                        break;
                        } else {
-                               if (data->cy == 0 &&
+                               if (py == 0 ||
+                                   (data->cy == 0 &&
                                    (screen_hsize(data->backing) == 0 ||
                                    data->oy >=
-                                   screen_hsize(data->backing) - 1))
+                                   screen_hsize(data->backing) - 1)))
                                        goto out;
-                               py--;

-                               py = screen_hsize(data->backing) + data->cy -
-                                   data->oy;
+                               py--;
                                px = window_copy_find_length(wme, py);

                                /* Stop if separator at EOL. */
```

* Platform (`uname -sp`).
Linux x86_64
* $TERM inside and outside of tmux (`echo $TERM`).
screen-256color, xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by nicm** [comment]
Does this still happen with master?

**Comment by ofdeath** [comment]
Yes, it still happens with master

**Comment by nicm** [comment]
It does not happen for me. Are you sure you restarted tmux entirely after you upgraded?

**Comment by ofdeath** [comment]
Oh, really? I have restarted tmux server entirely several times.
Maybe I need to restart the tmux server without plugins.

**Comment by nicm** [comment]
What does `tmux display -p '#{version}'` show?

**Comment by ofdeath** [comment]
It's `3.1b` for 3.1b and `next-3.3` for master

I think some plugin makes the problem. I've tested it with clean tmux.conf - only with below options - 
and it works without above problem.
I'll check the plugins. Thank you~

```
set-option -g mouse on
set-option -g word-separators " ,\"'[](){}<>=:@"
```

**Comment by ofdeath** [comment]
Oops, it still happens with 3.1b
I'm using below yank script for clipboard copy on remote session.
I don't know it's related with the yank script.

tmux.conf
```
set-option -g mouse on
set-option -g set-clipboard off
set-option -g word-separators " ,\"'[](){}<>=:@"

# tmux 2.4 or newer
# transfer copied text to attached terminal with yank
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'yank > #{pane_tty}'

bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'yank > #{pane_tty}'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'yank > #{pane_tty}'

bind-key -n DoubleClick1Pane select-pane \; copy-mode -M \; send-keys -X select-word
bind-key -n TripleClick1Pane select-pane \; copy-mode -M \; send-keys -X select-line
#bind -n DoubleClick1Pane select-pane \; copy-mode -M \; send-keys -X select-word \; send-keys -X copy-pipe 'yank > #{pane_tty}'
#bind -n TripleClick1Pane select-pane \; copy-mode -M \; send-keys -X select-line \; send-keys -X copy-pipe 'yank > #{pane_tty}'

bind-key -T copy-mode-vi DoubleClick1Pane select-pane \; send-keys -X select-word
bind-key -T copy-mode-vi TripleClick1Pane select-pane \; send-keys -X select-line

# transfer most-recently copied text to attached terminal with yank
bind-key -n M-y run-shell 'tmux save-buffer - | yank > #{pane_tty}'

# transfer previously copied text (chosen from a menu) to attached terminal
bind-key -n M-Y choose-buffer 'run-shell "tmux save-buffer -b \"%%%\" - | yank > #{pane_tty}"'
```

yank
```
#!/bin/sh
#
# Usage: yank [FILE...]
#
# Copies the contents of the given files (or stdin if no files are given) to
# the terminal that runs this program.  If this program is run inside tmux(1),
# then it also copies the given contents into tmux's current clipboard buffer.
# If this program is run inside X11, then it also copies to the X11 clipboard.
#
# This is achieved by writing an OSC 52 escape sequence to the said terminal.
# The maximum length of an OSC 52 escape sequence is 100_000 bytes, of which
# 7 bytes are occupied by a "\033]52;c;" header, 1 byte by a "\a" footer, and
# 99_992 bytes by the base64-encoded result of 74_994 bytes of copyable text.
#
# In other words, this program can only copy up to 74_994 bytes of its input.
# However, in such cases, this program tries to bypass the input length limit
# by copying directly to the X11 clipboard if a $DISPLAY server is available;
# otherwise, it emits a warning (on stderr) about the number of bytes dropped.
#
# See http://en.wikipedia.org/wiki/Base64 for the 4*ceil(n/3) length formula.
# See http://sourceforge.net/p/tmux/mailman/message/32221257 for copy limits.
# See http://sourceforge.net/p/tmux/tmux-code/ci/a0295b4c2f6 for DCS in tmux.
#
# Written in 2014 by Suraj N. Kurapati and documented at http://goo.gl/NwYqfW

buf=$( cat "$@" )

# copy to tmux if possible
#test -n "$TMUX" && tmux set-buffer "$buf"

# copy to X11 if possible...
test -n "$DISPLAY" && printf %s "$buf" | { xsel -ib || xclip -sel c ;} && exit

# ...otherwise copy to terminal
len=$( printf %s "$buf" | wc -c ) max=74994
test $len -gt $max && echo "$0: input is $(( len - max )) bytes too long" >&2

esc="\033]52;c;$( printf %s "$buf" | head -c $max | base64 | tr -d '\r\n' )\a"
test -n "$TMUX" && esc="\033Ptmux;\033$esc\033\\"

printf "$esc"

# https://github.com/sunaku/home/blob/master/bin/yank
```

**Comment by ofdeath** [comment]
Below nearly clean tmux.conf only works with tmux master, not with tmux 3.1b
```
set-option -g mouse on
set-option -g word-separators " ,\"'[](){}<>=:@"
```

Does master branch have some patchs to support clipboard copy on remote session like above yank script?
The problem only happens with yank script and tmux.conf in previous comment.

Anyway I'll test tmux master again with my original tmux.conf without yank script tomorrow.
Thank you very much! 👍

**Comment by nicm** [comment]
If you cannot reproduce with master then it appears the problem is already fixed.

**Comment by ofdeath** [comment]
The problem still happends with below tmux.conf

```
set-option -g mouse on
set-option -g word-separators " ,\"'[](){}<>=:@"
bind-key -n DoubleClick1Pane select-pane \; copy-mode -M \; send-keys -X select-word
```

I think the command select-word still has a problem - it's reproduced with master.
Is above tmux.conf wrong? or could you check the command select-word again?

**Comment by nicm** [comment]
You are doing `copy-mode -M` which will pass the mouse event on to copy mode and since it is in the top line it will begin scrolling. Remove the `-M` from `copy-mode`.

**Comment by ofdeath** [comment]
It's not scrolling up anymore after I removed the '-M'
Thanks you!
