### ISSUE TITLE
Some recent commit breaks tmux-sessionist

### ISSUE THREAD

**Issue by reportaman** [tmux/tmux#2829]
### Issue description

I use [tmux-sessionist](https://github.com/tmux-plugins/tmux-sessionist) all the time to kill a session and switch to another using its ``<prefix>Shift-x`` keybinding. It seems like some commit in a day or two breaks its functionality in some way.

To reproduce the error shown below:
1. Make sure to have tmux-sessionist loaded in your tpm list
2. Kill-server and start tmux
3. When in tmux, press ``<prefix>Shift-x`` i.e ``<prefix>`` followed by capital ``X``
4. Press escape to cancel the prompt, it will print the error shown below.

The error happens even if one were to press ``y`` to kill currently attached session. Though to see that, make sure to start multiple tmux sessions before killing one, as the error message is printed in one of the panes only when tmux server is not killed.

```
/Users/reportaman/.tmux/plugins/tmux-sessionist/scripts/kill_session_prompt.sh '0' '$0'' returned 1
```

### Required information

Please provide the following information:

* tmux version (`tmux -V`) next-3.3 tested at commit https://github.com/tmux/tmux/commit/f2d4a1f02275e5b4f273a3228e0e9c099851dadd.
* Platform (`uname -sp`) Darwin arm.
* $TERM inside and outside of tmux (`echo $TERM`) xterm-256color, tmux-256color.

**Comment by reportaman** [comment]
Oh nevermind, I think it should be filed on tmux-sessionist. Your new functionality is to return the exit code of confirm-before, and that seems to be causing this...

**Comment by reportaman** [comment]
But wait... I am not able to fix it for all cases. Here's my change:

File https://github.com/tmux-plugins/tmux-sessionist/blob/master/scripts/kill_session_prompt.sh:
```
#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# global vars passed to the script as arguments
CURRENT_SESSION_NAME="$1"
CURRENT_SESSION_ID="$2"

main() {
	tmux confirm -p "kill-session ${CURRENT_SESSION_NAME}? (y/n)" "run '$CURRENT_DIR/kill_session.sh \'$CURRENT_SESSION_ID''"
}
main
exit 0
```

All I have changed is that I added ``exit 0`` at the bottom of the script. This fixed error printed for cancellation of confirm-before, but does not fix the error that is retuned when user presses ``y`` to actually kill the session (remember to open multiple sessions on same server before trying).

**Comment by nicm** [comment]
I cannot help you with this, you need to talk to the author of the script you are using.

**Comment by reportaman** [comment]
@nicm I did some more testing, this ``kill_session_prompt.sh`` calls ``kill_session.sh``. If I run ``>> ./kill-session.sh <sessionname>`` from the command line, it does not return any error. Error is retuned only when ``./kill-session.sh <sessionname>`` is called when confirm-before is called. Given we recently changed confirm-before to propagate error code, it would help if you could take a look. I don't see anything suspicious in any of his files.

**Comment by nicm** [comment]
You can add `-b` to `confirm-before` so it doesn't block, same as before.

**Comment by reportaman** [comment]
@nicm Adding ``-b`` to ``confirm-before`` causes error ``[server exited unexpectedly]``.

**Comment by nicm** [comment]
Whoops, this should fix that:
~~~~
--- cmd-confirm-before.c        13 Aug 2021 06:50:42 -0000      1.45
+++ cmd-confirm-before.c        17 Aug 2021 11:19:25 -0000
@@ -72,7 +72,7 @@ cmd_confirm_before_exec(struct cmd *self
                free(copy);
        }

-       cdata = xmalloc(sizeof *cdata);
+       cdata = xcalloc(1, sizeof *cdata);
        cdata->cmd = xstrdup(args->argv[0]);

        cmd_get_source(self, &cdata->pi.file, &cdata->pi.line);

**Comment by reportaman** [comment]
@nicm Yep, after applying your patch and just adding the switch ``-b`` to ``confirm-before`` fixes this completely. Btw, ``-b`` is still not in ``man tmux``.

**Comment by nicm** [comment]
OK great stuff.
