### ISSUE TITLE
error connecting to /private/var/folders/.../tmux-xxx/default (No such file or directory)

### ISSUE THREAD

**Issue by abhiomkar** [tmux/tmux#284]
Hi, I'm not able to execute any tmux commands on my Mac. It throws below error.

```
$ tmux ls
error connecting to /private/var/folders/nj/9mg28n_j6jz4cdjyqtm5v8sc00_wl0/T/tmux-356960/default (No such file or directory)
```

Any idea? Thanks!

**Comment by nicm** [comment]
probably Apple changed something again, try tmux from git master, it doesn't use TMPDIR anymore

**Comment by abhiomkar** [comment]
is it possible to configure tmux to use other directory?

**Comment by nicm** [comment]
Set TMUX_TMPDIR.

**Comment by padde** [comment]
I fixed this by deleting the `/private/var/folders/.../tmux-xxx` folder.  After that everything worked normal again.

**Comment by modernlegend** [comment]
@padde 👍 thanks broseidon

**Comment by janzenz** [comment]
This happened to me after restarting my machine and lost all my sessions. Is there a way to keep my tmux sessions?

**Comment by lanox** [comment]
this happens to me as well on every reboot or on new install. 
I am running tmux: stable 2.3 (bottled), HEAD

**Comment by kleinjm** [comment]
Same here on restart

**Comment by janzenz** [comment]
I addressed this using [tmux-resurrect](https://github.com/tmux-plugins/tmux-resurrect)

**Comment by maryamkwlabs** [comment]
In my case, this message was not actually a problem! I just did not have any already-created sessions! After creating a session and then calling `tmux ls`, this message was not showing up again!

**Comment by henryhu712** [comment]
I delete the /private/var/folders/.../tmux-xxx folder. The issue still existed for 'tmux ls'. I started another session with 'tmux', exited it, then the issue fixed.
