### ISSUE TITLE
bug and fine-tuning of mouse support in `choose-tree` previews

### ISSUE THREAD

**Issue by DJCrashdummy** [tmux/tmux#3242]
### Issue description

this is just an idea to extend #1127 and bring the mouse support in `choose-tree` kind of to the next level. but i have no strong feelings about that, so i understand if it is to hard or laborious to implement it.

as a casual user of tmux i would have guessed that with mouse support enabled - since switching windows via status line and panes is possible via a simple click - also clicking on a distinct pane preview will get me there, but this is unfortunately not the case.

my suggestions:
- [ ] pane preview: switch to the appropriate window and activate the chosen pane as soon as i click on its preview instead of doing nothing. - *(simply exact the same behavior as i would hit enter.)*
- window preview: it would be awesome to have the ability to directly switch to the chosen window **and** pane by clicking on it. IMHO there are a few possible ways to accomplish this...
  - [ ] either similar as described for the pane preview by a single click on the area of the preview of the desired pane
  *(which would eliminate the ability to only switch the window and not change the active pane via mouse in `choose-tree`)*;
  - [ ] or simply still use a single click to just enter the window as it was and a double click to also switch the active pane
  *(since double clicks are also used to switch to a desired item via the list)*;
  - [ ] or also don't really change anything for the single click action, except if you intentionally click on the area of the index number in the middle of their preview
  *(although this behavior would seem a little bit odd to me)*.
- [ ] session preview: i have to admit that i haven't given this one too much thoughts... but it seems reasonable to me to do the same with windows as with panes in the window preview and simply stay with the last active pane *(as there is no possibility to select a pane in the session preview)*.

### Required information

* tmux version (`tmux -V`): `tmux 3.3a`
* Platform (`uname -sp`): `Linux unknown`
* $TERM inside and outside of tmux (`echo $TERM`): `tmux-256color` & `xterm-256color`
* Logs from tmux (`tmux kill-server; tmux -vv new`).

**Comment by DJCrashdummy** [comment]
**"interesting"**...: when using exact the same `.tmux.conf` with `tmux 2.9a` on a different machine (`Linux x86_64`, `screen` & `xterm`) the suggested functions at least for the session & window preview (the first variant) are already there, only clicking on a pane preview still does nothing. :raised_eyebrow:

am i messing something up or did i find an unintentional regression? i'm a little bit puzzled...

**Comment by DJCrashdummy** [comment]
another odd thing i noticed:
if you have the time at display in a pane before entering the  `choose-tree -Z` view, it disappears shortly after you try to switch panes via click on an other preview than the currently active pane (in the window preview).
if you choose the currently active pane again or even if you switch windows, the time stays there. and no mater what action you take via the list (keyboard **and** mouse!) it's also fine.

...so i'm pretty sure there is something fishy going on with the (not) switching via clicking on a preview.

**Comment by nicm** [comment]
This should be fixed in OpenBSD now, please try in a few hours once GitHub syncs up. Thanks!

**Comment by DJCrashdummy** [comment]
well... first, clicking on a single pane preview still does nothing. :disappointed: 

but... the switching via click on a pane (in the window preview) or clicking on a window in the session preview works nearly flawless (again). :tada: 
the only thing which is still odd is, that the time on display still disappears in some cases, but now i found the real reason behind it:
no mater if you switch panes, windows or session, **the time in the pane under the mouse pointer vanishes**, no mater what pane is/was or gets active... **but** interestingly this pane does not get active (as you would expect it because of an incorrect second click), but the correct one which was selected in the preview. - this behavior only occurs when switching via click on a preview, when switching via keyboard everything is fine as expected.
it is not a big deal (since it doesn't seem to affect any major function) but still a pretty strange behavior i noticed which - as a nitpicker - gets me a tiny little bit off. :stuck_out_tongue_winking_eye: 

---

unfortunately i found another bug concerning the `choose-tree` preview:
as far as i know, there shouldn't be a preview when using `choose-tree -w`... first everything looks fine as it should, but as soon as you expand **more** than one window, **the preview appears**. funnily if you collapse all or all but one window, the preview disappears again.
-> if this is intentionally (which i doubt), this makes absolutely no sense, since with more windows or sessions expanding, you have less space left for a proper preview.
BTW: this seems to only come in effect with windows, because with 2 sessions expanded, the previews don't show up.
