### ISSUE TITLE
macos sierra: [warn]: kq_init: detected broken kqueue; not using.: File exists

### ISSUE THREAD

**Issue by oschrenk** [tmux/tmux#475]
When listing sessions without any session running the command fails with one warning (I'm using fish that is why there is `echo $status` instead of `echo $?`). Not sure if non-zero exit was actually standard behaviour if there was no attached session

```
tmux list-sessions
[warn] kq_init: detected broken kqueue; not using.: File exists
0: 1 windows (created Sat Jul  9 11:55:19 2016) [204x41] (attached)
echo $status
1
```

When listing sessions with at least one sessions running, the command exits with 0, still with warning

```
tmux list-sessions
[warn] kq_init: detected broken kqueue; not using.: File exists
0: 1 windows (created Sat Jul  9 11:55:19 2016) [204x41] (attached)
```

I found an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=626534) for Chromium and libevent that might shed some further light onto this.

This behaviour breaks tmuxp to load sessions.

**Comment by nicm** [comment]
Using my amazing mind reading powers I can conclude that you are using tmux 2.2.

kqueue is broken on OS X, but we accidentally stopped turning it off in 2.2. Use tmux from Git instead, or export EVENT_NOKQUEUE=1 before starting any tmux.

**Comment by oschrenk** [comment]
You're a magician! (and sorry for not posting this info)

**Comment by jianbin-wei** [comment]
I noticed this issue yesterday and didn't have time to debug.  I also saw the Chromium issue and was trying to file an issue for tmux and saw this one.  Save me time. ;-)

**Comment by mvanbaak** [comment]
For those that come here because they have the same problem:

`brew uninstall --force tmux`
`brew install --HEAD tmux`

**Comment by keith** [comment]
This has been fixed in libevent as well so these warnings should be totally gone if you upgrade https://github.com/libevent/libevent/issues/376

**Comment by jakirkham** [comment]
FTR was this fixed in 2.3?

**Comment by prash16** [comment]
It doesnt fixes for me. I have a Mac, same error. Any suggestions

**Comment by Muniamur** [comment]
I updated Libevent and it didn't fix the issue.

This is a onetime fix (when I open terminal during the next session the error returns obviously):
```
export EVENT_NOKQUEUE=1
```

Any more permanent solutions?
