### ISSUE TITLE
"Not in a mode" regression when using mouse wheel

### ISSUE THREAD

**Issue by wincent** [tmux/tmux#638]
Somewhere between 2.3 and current master (13f1a922e180bc8) I've started observing a regression in mouse wheel behavior:

- `$TERM` inside tmux is `screen`.
- `$TERM` outside tmux is `xterm-256color`.
- OS is macOS 10.11.6.
- Terminal is iTerm2 (3.0.12).
- `~/.tmux.conf` contains only `set -g mouse on`.

To repro: 

1. Start a new session.
2. Split (for example with `Prefix-%`).
3. Move mouse over the unfocused pane.
4. Try scrolling with the mouse wheel.
5. See "Not in a mode" printed (happens only when scrolling down, not up; additionally, once it is in this state, clicking in the unfocused pane does not select or focus it, but it remains in copy mode).

I am not sure if this is a bug in tmux, or in the default mouse-related bindings:

```
$ tmux list-keys|egrep -i 'mouse|wheel|click'
bind-key    -T copy-mode    MouseDrag1Pane    send-keys -X begin-selection
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode    WheelUpPane       send-keys -X -N 5 scroll-up
bind-key    -T copy-mode    WheelDownPane     send-keys -X -N 5 scroll-down
bind-key    -T copy-mode    DoubleClick1Pane  send-keys -X select-word
bind-key    -T copy-mode    TripleClick1Pane  send-keys -X select-line
bind-key    -T copy-mode-vi MouseDrag1Pane    send-keys -X begin-selection
bind-key    -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode-vi WheelUpPane       send-keys -X -N 5 scroll-up
bind-key    -T copy-mode-vi WheelDownPane     send-keys -X -N 5 scroll-down
bind-key    -T copy-mode-vi DoubleClick1Pane  send-keys -X select-word
bind-key    -T copy-mode-vi TripleClick1Pane  send-keys -X select-line
bind-key    -T root         MouseDown1Pane    select-pane -t = ; send-keys -M
bind-key    -T root         MouseDown1Status  select-window -t =
bind-key    -T root         MouseDown3Pane    if-shell -F -t = #{mouse_any_flag} "select-pane -t=; send-keys -M" "select-pane -mt="
bind-key    -T root         MouseDrag1Pane    if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
bind-key    -T root         MouseDrag1Border  resize-pane -M
bind-key    -T root         WheelUpPane       if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if -Ft= "#{pane_in_mode}" "send-keys -M" "copy-mode -et=""
bind-key    -T root         WheelUpStatus     previous-window
bind-key    -T root         WheelDownStatus   next-window
```

I tried bisecting this, but unfortunately there were a number or revisions that I had to skip because I don't know how to build them (there is no `autogen.sh`, and if I just run `./configure` on them I don't get a working `Makefile`). In any case, here is the output of the bisect run from 2.3 (good) to `master` (bad):

```
# bad: [13f1a922e180bc8345a32929bbaa74f307569081] Merge branch 'obsd-master'
# good: [52869ed182482c26163799a7215139f4d81b6fca] Release tmux 2.3
git bisect start 'master' '2.3'
# skip: [382e09bed1bcf83eed98a36afa15f7dc9de18e72] Make an empty state on error rather than leaving something partially created (which now is now a fatal() later).
git bisect skip 382e09bed1bcf83eed98a36afa15f7dc9de18e72
# skip: [a0998e42b77b05e58c9a34b6541dc95ad9e2290f] Make grid_clear_cell set up the entry properly for 256 and RGB cells.
git bisect skip a0998e42b77b05e58c9a34b6541dc95ad9e2290f
# good: [215d3f8c0d0a604f138b976b2e49ce3fe1a50eb2] Merge branch 'obsd-master'
git bisect good 215d3f8c0d0a604f138b976b2e49ce3fe1a50eb2
# skip: [353439aceeed6ab311a74fc38f15276f72c654a4] enum values need to fit in 32 bits; we only use enum for numbering and Unicode characters fit in 24 bits, so we can leave key_code as 64 bits and change KEYC_BASE down to 0x10000000.
git bisect skip 353439aceeed6ab311a74fc38f15276f72c654a4
# good: [226b6a21929a9ea6b90152aecae4916eae7da005] Merge branch 'obsd-master'
git bisect good 226b6a21929a9ea6b90152aecae4916eae7da005
# skip: [8b804fb5894b6717de36c5c9c96f7fd29b14a864] Support UTF-8 entry into the command prompt.
git bisect skip 8b804fb5894b6717de36c5c9c96f7fd29b14a864
# bad: [9d58febc8f4243ed4a392e45f89de0455c032090] Merge branch 'obsd-master'
git bisect bad 9d58febc8f4243ed4a392e45f89de0455c032090
# skip: [4179b4242411f41a22d9743b4eff3b19ef69b3e8] Add support for BCE (background colour erase). This makes various escape sequences (notable EL and ED but also IL, DL, ICH, DCH) create blank cells using the current background colour rather than the default colour.
git bisect skip 4179b4242411f41a22d9743b4eff3b19ef69b3e8
# skip: [40253048ca6d6ecf45be24a76220d6012aca9818] bind-key -c has gone, remove from man page, and unused table declarations.
git bisect skip 40253048ca6d6ecf45be24a76220d6012aca9818
# skip: [66b5477cc1909e57489f854939a524ce2cd0f479] Do not allow the opposite pane to resize when dragging with the mouse because it is not possible to keep the mouse on the border when the minimum size is reached.
git bisect skip 66b5477cc1909e57489f854939a524ce2cd0f479
# skip: [e83ebf50de7503b96203df9a4b2badf2c649b031] Fix a couple of problems with insert mode: flush dirty cells before we modify the screen, not after; and use grid_view_insert_cells to make space not grid_move_cells.
git bisect skip e83ebf50de7503b96203df9a4b2badf2c649b031
# bad: [33fbf82ac0623c53603462e17e0a2eda489867e4] Merge branch 'obsd-master'
git bisect bad 33fbf82ac0623c53603462e17e0a2eda489867e4
# skip: [1bd08f903b8f70b0dd9aad577f830d944b969516] Remove mention of key tables than no longer exist.
git bisect skip 1bd08f903b8f70b0dd9aad577f830d944b969516
# bad: [76a9e6f27bb0c7b547989c3b80cf8cc0a148064d] NetBSD needs _OPENBSD_SOURCE for reallocarray.
git bisect bad 76a9e6f27bb0c7b547989c3b80cf8cc0a148064d
# skip: [85d7afaefc1e2cf8008575a776ec70f51d24e1a6] Support double and triple clicks (they are cumulative, so double is fired then triple), and use for select-word and select-line in copy mode. Inspired by a different solution from Omar Sandoval.
git bisect skip 85d7afaefc1e2cf8008575a776ec70f51d24e1a6
# skip: [e45401846f0a423bb90ebd3943041a28b2657631] Add static in window-*.c and move some internal functions out of tmux.h.
git bisect skip e45401846f0a423bb90ebd3943041a28b2657631
# bad: [b9dc855016cf79c8bb8469c272dbc6bca24deadc] Merge branch 'obsd-master'
git bisect bad b9dc855016cf79c8bb8469c272dbc6bca24deadc
# skip: [76d6d3641f271be1756e41494960d96714e7ee58] Fundamental change to how copy mode key bindings work:
git bisect skip 76d6d3641f271be1756e41494960d96714e7ee58
# good: [27126f87976c63161fcae2ab1eb9c6df726a84ff] Merge branch 'obsd-master'
git bisect good 27126f87976c63161fcae2ab1eb9c6df726a84ff
# skip: [a81685bfac9d4eac3a7cfd8f8ce13033a46fe01c] Add static in cmd-* and fix a few other nits.
git bisect skip a81685bfac9d4eac3a7cfd8f8ce13033a46fe01c
# skip: [5c49e1d0c1afaf98512b2ffd1f31d91fecff9851] Some other stuff that can be local to one file.
git bisect skip 5c49e1d0c1afaf98512b2ffd1f31d91fecff9851
# skip: [c426e485e527a03aa3b4bdbb3203f621e006cbd5] Loads more static, except for cmd-*.c and window-*.c.
git bisect skip c426e485e527a03aa3b4bdbb3203f621e006cbd5
# only skipped commits left to test
# possible first bad commit: [b9dc855016cf79c8bb8469c272dbc6bca24deadc] Merge branch 'obsd-master'
# possible first bad commit: [5c49e1d0c1afaf98512b2ffd1f31d91fecff9851] Some other stuff that can be local to one file.
# possible first bad commit: [e45401846f0a423bb90ebd3943041a28b2657631] Add static in window-*.c and move some internal functions out of tmux.h.
# possible first bad commit: [85d7afaefc1e2cf8008575a776ec70f51d24e1a6] Support double and triple clicks (they are cumulative, so double is fired then triple), and use for select-word and select-line in copy mode. Inspired by a different solution from Omar Sandoval.
# possible first bad commit: [76d6d3641f271be1756e41494960d96714e7ee58] Fundamental change to how copy mode key bindings work:
# possible first bad commit: [8b804fb5894b6717de36c5c9c96f7fd29b14a864] Support UTF-8 entry into the command prompt.
# possible first bad commit: [a81685bfac9d4eac3a7cfd8f8ce13033a46fe01c] Add static in cmd-* and fix a few other nits.
# possible first bad commit: [c426e485e527a03aa3b4bdbb3203f621e006cbd5] Loads more static, except for cmd-*.c and window-*.c.
```

I don't know if logs will be useful in this case, but attaching them anyway: [logs.zip](https://github.com/tmux/tmux/files/585068/logs.zip)

**Comment by nicm** [comment]
One of the commands must be using the wrong target (active pane not the mouse pane).

**Comment by wincent** [comment]
The commands (all coming from defaults) look reasonable to me, but I might be missing something. [This one](https://github.com/tmux/tmux/blob/afdef6d122ab667a48b843af74541e9aafcf98e6/key-bindings.c#L234), defined in `key-bindings.c`, is likely relevant, but it looks ok to me (note the use of `-t=`:

```
bind -n WheelUpPane if-shell -Ft= '#{mouse_any_flag}' 'send-keys -M' 'if -Ft= "#{pane_in_mode}" "send-keys -M" "copy-mode -et="'
```

I'm wondering if there is a bug somewhere related to distinguishing the active vs mouse pane, because as I noted above, when it is in this state, normal click events don't work properly either.

**Comment by nicm** [comment]
Yes it is a bug.

**Comment by nicm** [comment]
Does this fix it? 
[x.diff.txt](https://github.com/tmux/tmux/files/592141/x.diff.txt)

**Comment by wincent** [comment]
@nicm: In my brief testing, it does seem to fix it, at least for a vanilla test case:

```
./tmux -f /dev/null new
tmux set -g mouse on
```

**Comment by wincent** [comment]
Still some quirks in the default config, I think. With `-f /dev/null` and `tmux set -g mouse on` as above:

1. Open two splits, A and B.
2. Focus A by clicking, focus B by clicking (both work).
3. Enter copy mode in B by scrolling.
4. Focus A by clicking (does nothing; but focuses if you click again).
5. Focus B by clicking (works on first click).

You can repeat 4 and 5. It takes two clicks to focus pane A which is not in copy mode, and one click to focus pane B, which is. I tested this in both iTerm and Terminal.app on macOS.

I can also see some weirdness if I put both pane A and B in copy mode. Then clicking in either one doesn't select that pane.

I have a more complicated configuration (quoted below) that seems to avoid those issues, so I am not blocked by this, but it would be nice if the default config had as few wrinkles and sharp edges as possible:

```
bind-key    -T copy-mode    MouseDrag1Pane    send-keys -X begin-selection
bind-key    -T copy-mode    MouseDragEnd1Pane send-keys -X copy-selection-and-cancel
bind-key    -T copy-mode    WheelUpPane       send-keys -X -N 5 scroll-up
bind-key    -T copy-mode    WheelDownPane     send-keys -X -N 5 scroll-down
bind-key    -T copy-mode    DoubleClick1Pane  send-keys -X select-word
bind-key    -T copy-mode    TripleClick1Pane  send-keys -X select-line
bind-key    -T copy-mode-vi MouseDown1Pane    select-pane -t {mouse} ; send-keys -M
bind-key    -T copy-mode-vi MouseDrag1Pane    send-keys -X -t {mouse} begin-selection
bind-key    -T copy-mode-vi WheelUpPane       send-keys -X -t {mouse} clear-selection ;send-keys -X -N 3 -t {mouse} scroll-up
bind-key    -T copy-mode-vi WheelDownPane     send-keys -X -t {mouse} clear-selection ;send-keys -X -N 3 -t {mouse} scroll-down
bind-key    -T copy-mode-vi DoubleClick1Pane  send-keys -X -t {mouse} select-word
bind-key    -T copy-mode-vi TripleClick1Pane  send-keys -X -t {mouse} select-line
bind-key    -T root         MouseDown1Pane    select-pane -t = ; send-keys -M
bind-key    -T root         MouseDown1Status  select-window -t =
bind-key    -T root         MouseDown3Pane    if-shell -F -t = #{mouse_any_flag} "select-pane -t=; send-keys -M" "select-pane -mt="
bind-key    -T root         MouseDrag1Pane    if-shell -F -t = #{mouse_any_flag} "if -Ft= "#{pane_in_mode}" "copy-mode -M" "send-keys -M"" "copy-mode -M"
bind-key    -T root         MouseDrag1Border  resize-pane -M
bind-key    -T root         WheelUpPane       if-shell -F -t = #{mouse_any_flag} "send-keys -M" "if -Ft= "#{pane_in_mode}" "send-keys -M" "copy-mode -et=""
bind-key    -T root         WheelUpStatus     previous-window
bind-key    -T root         WheelDownStatus   next-window
bind-key    -T root         DoubleClick1Pane  if-shell -F -t {mouse} #{alternate_on} "send-keys -M" "copy-mode -t{mouse}; send-keys -t{mouse} -X select-word"
bind-key    -T root         TripleClick1Pane  if-shell -F -t {mouse} #{alternate_on} "send-keys -M" "copy-mode -t{mouse}; send-keys -t{mouse} -X select-line"
```

**Comment by nicm** [comment]
Is this fixed by https://github.com/tmux/tmux/pull/651?

**Comment by nicm** [comment]
Please try this instead of the key bindings changes, it should get rid of the need for -t= on mouse key bindings: [abc.diff.txt](https://github.com/tmux/tmux/files/594345/abc.diff.txt)

**Comment by wincent** [comment]
#651 doesn't seem to fix it (just tried `HEAD`, ie. 759953cb8d6e8ac2e95f831a).

1. Create panes A and B; B is focused.
2. Enter copy mode in B with mouse wheel.
3. Click in A; requires two clicks to focus.

Additionally:

1. Create panes A and B; B is focused.
2. Enter copy mode in B with mouse wheel.
3. Use mouse wheel over pane A; pane B scrolls instead of pane B.

Haven't tried your patch yet though; I'll do that now.

**Comment by wincent** [comment]
With the patch applied on top of `HEAD` we still require two clicks to focus, but the issue with the mouse wheel scrolling the wrong pane appears to be fixed.

**Comment by nicm** [comment]
But the key binding diff I sent does fix the two clicks thing?

**Comment by wincent** [comment]
I don't think so, I'll double check again now.

- Current `HEAD`: still requires two clicks.
- Current `HEAD` with abc.diff.txt applied on top: still requires two clicks.
- Current `HEAD` with abc.diff.txt *and* x.diff.txt applied on top: still requires two clicks.

All of those launched with ` ./tmux -f /dev/null new` and then `./tmux set -g mouse on`.

**Comment by nicm** [comment]
I have applied my fix for the -t= thing, please test it when it makes it to GitHub and be sure that it fixes the problem.

The problem with the multiple clicks appears to be that we are looking for the mouse key too early, before the pane, window, session has been established. So it is not really valid and sometimes looks up the wrong key table (from the previous mouse click).

If we fix that then we can end up sending mouse keys to a pane that isn't the active one. This was how I intended it to work, but it does mean we need to add select-pane to the key bindings. Perhaps this should be implicit, although I think it is more flexible to make it explicit.

Anyway, please try this: [x.diff.txt](https://github.com/tmux/tmux/files/609552/x.diff.txt)

**Comment by wincent** [comment]
That diff on top of master (8a80013) fixes the double-click to select issue in a vanilla session (`./tmux -f /dev/null new` and then `./tmux set -g mouse on`). It does, however break click-to-select a pane that is in copy mode; ie:

Without the patch:

1. Create panes A and B; B is focused.
2. Enter copy mode in B with mouse wheel.
3. Click in A; requires two clicks to focus.
4. Click in B; it focuses.

With the patch:

1. Create panes A and B; B is focused.
2. Enter copy mode in B with mouse wheel.
3. Click in A; it focuses (yay).
4. Click in B; it does not focus with any number of clicks (boo), although other actions work (like double click to select word etc).

**Comment by nicm** [comment]
This is because the copy-mode table has no binding for MouseDown1Pane, try this:

bind -Tcopy-mode MouseDown1Pane select-pane

**Comment by wincent** [comment]
Doesn't work, I'm afraid. (Nothing happens on click.)

**Comment by nicm** [comment]
It works for me, are you sure you are using Emacs keys?

**Comment by wincent** [comment]
vi vs emacs shouldn't make a difference here, as I am starting tmux with `./tmux -f /dev/null new`, and Emacs mode is the default, isn't it?

/me Reads man page

Doh.

> The default is emacs, *unless* VISUAL or EDITOR contains `vi'.

`EDITOR` is "vim", so when I thought I was testing in emacs mode I was actually testing in vi mode.

Confirmed that that fixes it with `./tmux set -g mode-keys emacs`.

**Comment by choco** [comment]
With latest master the "not in mode" seems to be fixed, but I have and edge case when a mouse scroll still gets to the wrong panel.
With standard configuration and bindings and two panes
```
_________________________________
|               |               |
|               |               |
|       1       |       2       |
|               |               |
|               |               |
|_______________|_______________|
```
Steps:
1. select pane 1 and enter copy mode
2. move cursors above pane 2 and perform a scroll, pane 3 enters copy mode and scrolls correctly but pane 1 that is selected and was already in copy mode gets one scroll event ( even though scroll event is being performed on pane 2)

**Comment by nicm** [comment]
I have applied my last diff now, it should be in GitHub soon, please test once it has synced and let me know if there are still problems:

~~~~~
----------------------------
revision 1.202
date: 2016/11/24 13:46:50;  author: nicm;  state: Exp;  lines: +15 -8;  commitid: AE4rxCQLpL805vhq;
Fix so that we work out the right pane from mouse events - we were doing
so too early, before the mouse event was necessarily valid, so could end
up using the pane from the previous mouse event, or the active pane.

It is important that we use the right pane now that different panes can
have different key tables (for copy mode).

Fixes problem reported by Greg Hurrell.

**Comment by pmalek** [comment]
For me exchanging `set -g @plugin 'tmux-plugins/tmux-copycat'` for `set -g @plugin 'thalesmello/tmux-copycat'` fixed the issue.
